name: Hello

on: 
  workflow_dispatch: 

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello From Github Actions $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show the version of python, docker
        run: docker --version && python --version
